-- Upgrade script for Reporting Schema from DM 3.3 (3.3.0.747) to DM 4.0


--==========ALTER TABLES==========
ALTER TABLE dmrs_attributes MODIFY relationship_id VARCHAR2(100);
ALTER TABLE dmrs_key_attributes MODIFY relationship_id VARCHAR2(100);
ALTER TABLE dmrs_large_text MODIFY object_id VARCHAR2(80);
ALTER TABLE dmrs_mappings MODIFY logical_object_id VARCHAR2(80);

--=========INDEXES==========
CREATE INDEX DESIGNS__IDX ON DMRS_DESIGNS (DESIGN_ID, DESIGN_OVID, DESIGN_NAME, VERSION_COMMENTS, DATE_PUBLISHED) NOLOGGING;
DROP INDEX MODELS_NAME_IDX;
CREATE INDEX MODELS_NAME_IDX ON DMRS_MODELS (MODEL_OVID, MODEL_NAME, MODEL_TYPE) NOLOGGING;
CREATE INDEX DIAGRAMS_NAME_IDX ON DMRS_DIAGRAMS (OVID, DIAGRAM_NAME, DIAGRAM_TYPE, IS_DISPLAY) NOLOGGING;
CREATE INDEX DIAGRAM_ELEMENTS_NAME_IDX ON DMRS_DIAGRAM_ELEMENTS (NAME, OVID, TYPE, MODEL_OVID, DIAGRAM_OVID) NOLOGGING;